FROM ubuntu:18.04
RUN apt-get update \
    && apt-get install -y apache2
RUN echo "TEST WEB"> /var/www/html/index.html
EXPOSE 80
CMD [ "/usr/sbin/apache2ctl", "-DFOREGROUND" ]
LABEL maintainer="Seongmi Lee <zyle1104@gmail.com>"
# install apache
